# -*- coding: utf-8 -*-
"""Day 1 code .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NIb0kbV2SaVIay67WgkIG0Fhsid-djWk
"""

print("Let's Install EC2 Instance with the help of CLI platform without using any browser")

pip install boto3

import boto3

myec2 = boto3.resource(
            service_name="ec2",
            region_name="ap-south-1" ,
            aws_access_key_id="****************",
            aws_secret_access_key="********************************"
)





def osTerminate(n):
    myec1.terminate_instances(InstanceIds=[n])





def osLaunch():
    myid = myec2.create_instances(
                InstanceType="t2.micro",
                ImageId="ami-0fd05997b4dff7aac",
                MinCount=1,
                MaxCount=1
    )

    return myid

myos = osLaunch()

myos[0].id

myoslist = []

myoslist.append( myos[0].id )

myoslist

myos = osLaunch()

myoslist.append( myos[0].id )

len(myoslist)

myec1 = boto3.client("ec2",region_name="ap-south-1" ,
            aws_access_key_id="****************",
            aws_secret_access_key="****************************")

def osTerminate(id):
    # Pass InstanceIds as a list containing the id
    myec1.terminate_instances(InstanceIds=[id])
    return myoslist.pop()

# # Pass InstanceIds as a list containing the instance ID
# myec1.terminate_instances(InstanceIds=["i-0fb144ad3c494197a"])

myoslist

osTerminate(myoslist[-1])

myoslist